config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  root to: 'welcome#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
    #enum status: { todo: 0, doing: 1, done: 2}
    #belongs_to :parent_task, class_name: 'Task'
    #has_many :tasks
    validates :content, presence: true
    
    def getActualHour
        diff_sec = self.end_task.to_time - self.start_task.to_time
        diff_date = Time.at(diff_sec)
        actual_hour =  (diff_date.day-1)*24 + diff_date.hour + diff_date.min / 60.0
        
        return actual_hour.round(2)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @graph_data =[]
    @tasks.each do |t|
      if(!t.expected_hour.nil?)
        @graph_data.push [t.start_task.to_date, ((t.getActualHour-t.expected_hour)/t.expected_hour)]
      end
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task)
      .permit(:content, :status, :start_task, :end_task, :expected_hour)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  
  <div class="field">
    <%= f.label :start_task %><br>
    <%= f.datetime_select :start_task, {},  class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :end_task %><br>
    <%= f.datetime_select :end_task, {},  class: 'form-control' %>
  </div>
  
  <div class="field">
    <%= f.label :expected_hour %><br>
    <%= f.number_field :expected_hour, step: 0.1%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Status</th>
      <th>start</th>
      <th>end</th>
      <th>expected[h]</th>
      <th>error</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.content %></td>
        <td><%= task.status %></td>
        <td><%= task.start_task %></td>
        <td><%= task.end_task %></td>
        <td><%= task.expected_hour %></td>
        <td><%= task.getActualHour %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
    <%= line_chart @graph_data %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>start:</strong>
  <%= @task.start_task %>
</p>

<p>
  <strong>end:</strong>
  <%= @task.end_task %>
</p>

<p>
  <strong>expected_hour:</strong>
  <%= @task.expected_hour %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/welcome/index.html.erb
<h1>Listing Tasks</h1>
<div id="container">
    
</div>